version: "3"

services:
  traefik:
    image: traefik:1.7.11
    restart: always
    ports:
      - 81:80
      - 444:443
    expose:
      - "444"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy"
      - "traefik.backend=traefik-dashboard"
      - "traefik.frontend.auth.basic=admin:$$apr1$$lHDfomvH$$42CgD8.GE3fLVkX0fSNS01"
      - "traefik.frontend.rule=Host:schedule.somervillebikekitchen.org;PathPrefix:/traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    container_name: traefik

  sbk-sched-web:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: unless-stopped
    ports:
      - 8081:8081
    expose:
      - "8081"
    networks:
      - proxy
      - default
    labels:
      - "traefik.backend=sbk-sched-web"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.port=8081"
      - "traefik.frontend.rule=Host:schedule.somervillebikekitchen.org"

  sbk-sched:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - proxy
      - default
    ports:
      - 3030:3030
    expose:
      - "3030"
    env_file:
      - ./docker-env.prod
    labels:
      - "traefik.backend=sbk-sched"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.port=3030"
      - "traefik.frontend.rule=Host:schedule.somervillebikekitchen.org;PathPrefixStrip:/api"

networks:
  proxy:
    external: true
