debug = true
logLevel = "DEBUG"

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
		[entryPoints.http.redirect]
  	 entryPoint = "https"
  [entryPoints.traefik-dashboard]
	 address = ":8080"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
		
[api]
entryPoint = "traefik-dashboard"
dashboard = true
debug = false
  [api.statistics]
  recentErrors = 10

[ping]
entryPoint = "traefik-dashboard"
      
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "schedule.somervillebikekitchen.org"
watch = true
exposedByDefault = false

[acme]
email = "admin@somervillebikekitchen.org"
storage = "acme.json"
entryPoint = "https"
acmeLogging = true
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
onHostRule = true
[[acme.domains]]
main = "schedule.somervillebikekitchen.org"

[acme.httpChallenge]
entryPoint = "http"

#[acme.tlsChallenge]
#entryPoint = "http"